#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("SharedPreferences.Resource", IsApplication=true)]

namespace SharedPreferences
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::Entity.Resource.String.ApplicationName = global::SharedPreferences.Resource.String.ApplicationName;
			global::Entity.Resource.String.Hello = global::SharedPreferences.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int slide_in_top = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int slide_out_bottom = 2130968577;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int button_email_style = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int buttonSignInStyle = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int checkbox_style = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int edit_text_style = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int ic_action_download = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int ic_action_overflow = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int ic_action_search = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_navigation_drawer = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int Icon = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int monoandroidsplash = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int progressbarStyle = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int xs = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080005
			public const int btnLogin = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int checkBox1 = 2131230726;
			
			// aapt resource value: 0x7f08001e
			public const int downloads = 2131230750;
			
			// aapt resource value: 0x7f08001b
			public const int etSearch = 2131230747;
			
			// aapt resource value: 0x7f08001d
			public const int etSearch1 = 2131230749;
			
			// aapt resource value: 0x7f08000b
			public const int item_subtitle = 2131230731;
			
			// aapt resource value: 0x7f08000c
			public const int item_title = 2131230732;
			
			// aapt resource value: 0x7f08001a
			public const int listView = 2131230746;
			
			// aapt resource value: 0x7f080019
			public const int llContainer = 2131230745;
			
			// aapt resource value: 0x7f08001c
			public const int llContainer1 = 2131230748;
			
			// aapt resource value: 0x7f080002
			public const int mainView = 2131230722;
			
			// aapt resource value: 0x7f080020
			public const int menu = 2131230752;
			
			// aapt resource value: 0x7f080008
			public const int progressBar1 = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int relativeLayout1 = 2131230727;
			
			// aapt resource value: 0x7f08000a
			public const int sample_content_fragment = 2131230730;
			
			// aapt resource value: 0x7f080009
			public const int sample_main_layout = 2131230729;
			
			// aapt resource value: 0x7f08001f
			public const int search = 2131230751;
			
			// aapt resource value: 0x7f080000
			public const int sliding_tabs = 2131230720;
			
			// aapt resource value: 0x7f080011
			public const int txtAla11 = 2131230737;
			
			// aapt resource value: 0x7f080012
			public const int txtAla12 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int txtAla13 = 2131230739;
			
			// aapt resource value: 0x7f080014
			public const int txtAla14 = 2131230740;
			
			// aapt resource value: 0x7f080015
			public const int txtAla15 = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int txtAla16 = 2131230742;
			
			// aapt resource value: 0x7f080017
			public const int txtAla17 = 2131230743;
			
			// aapt resource value: 0x7f080018
			public const int txtAla18 = 2131230744;
			
			// aapt resource value: 0x7f08000e
			public const int txtDeptName = 2131230734;
			
			// aapt resource value: 0x7f080004
			public const int txtPwd = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int txtUser = 2131230723;
			
			// aapt resource value: 0x7f080010
			public const int txtUserEmail = 2131230736;
			
			// aapt resource value: 0x7f08000d
			public const int txtUserName = 2131230733;
			
			// aapt resource value: 0x7f08000f
			public const int txtUserPwd = 2131230735;
			
			// aapt resource value: 0x7f080001
			public const int viewpager = 2131230721;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int fragment_sample = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Login = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int pager_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int row_testcase = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int row_testcase11 = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int row_testcase12 = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int TestCase = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int TestCase1 = 2130903048;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int action_bar = 2131165184;
			
			// aapt resource value: 0x7f070001
			public const int actionbar = 2131165185;
			
			// aapt resource value: 0x7f070002
			public const int actionbar_main = 2131165186;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int sample_hide_log = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int sample_show_log = 2131034114;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060001
			public const int CustomActionBarTheme = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int Mono_Android_Theme_Splash = 2131099648;
			
			// aapt resource value: 0x7f060002
			public const int MyActionBar = 2131099650;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
